name: GitHub Secret
on:
    workflow_dispatch:

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: print seccret
              run: |
                echo "My Top Secret: ${{ secrets.MY_TOP_SECRET }}"
            
            - name : Print secret as an env variable
              run: | 
                echo MY_TOP_SECRET: $MY_TOP_SECRET
        env:
            AZURE_CREDENTIAL: ${{ secrets.MY_TOP_SECRET }}